name: "Close stale issues and PRs"
on: 
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  stale:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: gorzelinski/stale@add-reaction-updates
        with:
          stale-issue-message: "Nobody has updated the issue since the last year. Now it is marked as stale and will be closed soon. We know it may be valid, so if you're interested in the solution, leave a comment or reaction."
          stale-pr-message: "Nobody has updated the PR since the last year. Now it is marked as stale and will be closed soon. We know it may be valid, so if you're interested in the contribution, leave a comment or reaction."
          days-before-stale: 1
          days-before-close: 1
          exempt-issue-labels: support
          exempt-pr-labels: support
          